-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 23:29:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema madang2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `madang2` ;

-- -----------------------------------------------------
-- Schema madang2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `madang2` DEFAULT CHARACTER SET utf8 ;
USE `madang2` ;

-- -----------------------------------------------------
-- Table `madang2`.`NewPublisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madang2`.`NewPublisher` (
  `pubname` VARCHAR(45) NOT NULL,
  `stname` VARCHAR(45) NULL,
  `officephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pubname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madang2`.`NewBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madang2`.`NewBook` (
  `bookid` INT NOT NULL,
  `bookname` VARCHAR(45) NOT NULL,
  `price` INT NULL,
  `pubname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bookid`),
  CONSTRAINT `fk_NewBook_NewPublisher`
    FOREIGN KEY (`pubname`)
    REFERENCES `madang2`.`NewPublisher` (`pubname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NewBook_NewPublisher_idx` ON `madang2`.`NewBook` (`pubname` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `madang2`.`NewCostomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madang2`.`NewCostomer` (
  `custid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`custid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madang2`.`NewBook_has_NewCostomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madang2`.`NewBook_has_NewCostomer` (
  `bookid` INT NOT NULL,
  `custid` INT NOT NULL,
  `orderdate` DATE NOT NULL,
  `saleprice` INT NOT NULL,
  `orderid` INT NOT NULL,
  PRIMARY KEY (`orderid`),
  CONSTRAINT `fk_NewBook_has_NewCostomer_NewBook1`
    FOREIGN KEY (`bookid`)
    REFERENCES `madang2`.`NewBook` (`bookid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NewBook_has_NewCostomer_NewCostomer1`
    FOREIGN KEY (`custid`)
    REFERENCES `madang2`.`NewCostomer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NewBook_has_NewCostomer_NewCostomer1_idx` ON `madang2`.`NewBook_has_NewCostomer` (`custid` ASC) VISIBLE;

CREATE INDEX `fk_NewBook_has_NewCostomer_NewBook1_idx` ON `madang2`.`NewBook_has_NewCostomer` (`bookid` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
