data eshop;
 infile 'C:\Users\FAMILY\Desktop\╫ех©╧н.csv';
 input yt;
 t=_n_;
 date=intnx('month','01jan2001'd,_n_-1);
 format date yymmd.;
 lnyt=log(yt);
run;
%logtest(eshop, yt, out=trans, print=yes);
goptions i=join;
data eshop0;
 set eshop;
 if _n_<245;
 dif_lnyt=dif(lnyt);
run;
proc gplot data=eshop0;
 plot yt*t;
 plot lnyt*t;
 plot dif_lnyt*t;
run;
proc arima data=eshop;
   identify var=lnyt nlag=72;
   identify var=lnyt(1) nlag=72;
   identify var=lnyt(1,12) nlag=72;
   estimate q=(1,1)(12) noint method=ml plot;
   forecast lead=12 out=out_eshop;
run;
data out_eshop;
 merge out_eshop eshop;
 date=intnx('month','01jan2001'd,_n_-1);
 format date yymmd.;
 trans_fore=exp(forecast);
run;
proc print data=out_eshop noobs;
 var date trans_fore;
 where '01jul2021'd<=date<='01jul2022'd;
run;
data out_eshop_;
 merge eshop out_eshop;
 by date;
 if date>='01jul2021'd then yt=.;
run;
proc gplot data out_eshop_;
 plot trans_fore*date;
run;
